---
- name: "Manage yum repositories"
  ansible.builtin.yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description | default(omit) }}"
    baseurl: "{{ item.baseurl | default(omit) }}"
    mirrorlist: "{{ item.mirrorlist | default(omit) }}"
    metalink: "{{ item.metalink | default(omit) }}"
    enabled: "{{ item.enabled | default(omit) }}"
    gpgcheck: "{{ item.gpgcheck | default(omit) }}"
    gpgkey: "{{ item.gpgkey | default(omit) }}"
    file: "{{ item.file | default(omit) }}"
    includepkgs: "{{ item.includepkgs | default(omit) }}"
    exclude: "{{ item.exclude | default(omit) }}"
    priority: "{{ item.priority | default(omit) }}"
    proxy: "{{ item.proxy | default(omit) }}"
    sslverify: "{{ item.sslverify | default(omit) }}"
    sslcacert: "{{ item.sslcacert | default(omit) }}"
    sslclientcert: "{{ item.sslclientcert | default(omit) }}"
    sslclientkey: "{{ item.sslclientkey | default(omit) }}"
    repo_gpgcheck: "{{ item.repo_gpgcheck | default(omit) }}"
    skip_if_unavailable: "{{ item.skip_if_unavailable | default(omit) }}"
    cost: "{{ item.cost | default(omit) }}"
    module_hotfixes: "{{ item.module_hotfixes | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ yum_repositories }}"
  loop_control:
    label: "{{ item.name }}"
  notify: "Clean package manager cache"
