---
- name: "Converge"
  hosts: all
  gather_facts: true
  pre_tasks:
    - name: "Skip on non-RedHat systems"
      ansible.builtin.meta: end_host
      when: ansible_os_family != 'RedHat'
  vars:
    yum_repository_files_absent:
      - local.repo
    yum_repositories:
      - name: epel
        description: Extra Packages for Enterprise Linux
        baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
        gpgcheck: true
        gpgkey: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-$releasever
        enabled: true
        state: present
  roles:
    - role: "dgibbs64.yum_repository"
