---
- name: "Converge"
  hosts: all
  gather_facts: false
  vars:
    yum_repositories:
      - name: epel
        description: Extra Packages for Enterprise Linux
        baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
        gpgcheck: true
        gpgkey: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-$releasever
        enabled: true
        state: present
  roles:
    - role: "dgibbs64.yum_repository"
