---
- name: "Verify"
  hosts: all
  gather_facts: false
  tasks:
    - name: "Check epel repo file exists"
      ansible.builtin.stat:
        path: /etc/yum.repos.d/epel.repo
      register: epel_repo_file

    - name: "Assert epel repo file exists"
      ansible.builtin.assert:
        that:
          - epel_repo_file.stat.exists
        quiet: true
