---
- name: "Verify"
  hosts: all
  gather_facts: true
  tasks:
    - name: "Skip on non-RedHat systems"
      ansible.builtin.meta: end_host
      when: ansible_os_family != 'RedHat'

    - name: "Check epel repo file exists"
      ansible.builtin.stat:
        path: /etc/yum.repos.d/epel.repo
      register: epel_repo_file

    - name: "Assert epel repo file exists"
      ansible.builtin.assert:
        that:
          - epel_repo_file.stat.exists
        quiet: true

    - name: "Check legacy repo files are absent"
      ansible.builtin.stat:
        path: "/etc/yum.repos.d/{{ item }}"
      register: legacy_repo_files
      loop:
        - local.repo
        - CentOS-Base.repo
        - random-cruft.repo

    - name: "Assert legacy repo files do not exist"
      ansible.builtin.assert:
        that:
          - not item.stat.exists
        quiet: true
      loop: "{{ legacy_repo_files.results }}"
      loop_control:
        label: "{{ item.item }}"
